namespace_id: "d7641b29-7426-4cdf-b94f-1e14844bc131"
host: "192.168.84.10"
port: 8848
data_id: "tk_products_srv.json"
group: "dev"
timeout_ms: 5000
not_load_cache_at_start: true
log_dir: "tmp/nacos/log"
cache_dir: "tmp/nacos/cache"
log_level: "debug"
